Drop @ratelimit Annotation, Create #[RateLimit] Attribute, Drop php7 support, Drop symfony 3 & 4 support
jaytaph/RateLimitBundle pull request #132
Opened 2023-05-25 14:20 UTC by axi

Should fix #130.

There is still (at least) one thing I would like somebody to check: the way I get Attributes in ```RateLimitAnnotationListener::getRateLimitsFromAttributes()```. I kind of mixed the ways I found in ```Symfony\Component\HttpKernel\Event\ControllerEvent::setController()```  & ```Symfony\Component\HttpKernel\Event\ControllerEvent::getAttributes()``` (sf6). I should maybe try to use getAttributes() method from ControllerEvent if it exists (sf6) and use my current implementation as a fallback for Sf5.4 ?

I tried to make it the most compatible possible.
Also, I added a condition for uploading coverage in ci but I must verify it still works for non forks.

Let me know what you think.

2023-05-25 14:21 UTC, axi commented
Hum, looks like upload coverage is also broken for main repository...

2023-06-13 17:36 UTC, axi commented
Something wrong with that pull request ?

2023-08-11 14:54 UTC, goetas requested changes
Overall this looks great! just two minor comments on my side

2023-08-11 14:54 UTC, goetas commented on EventListener/RateLimitAnnotationListener.php
> +        if ($event->getRequest()->attributes->has('_x-rate-limit')) {
nitpick: here you can extract `$event->getRequest()`  in a dedicated `$request` variable

2023-08-11 14:54 UTC, goetas commented on EventListener/RateLimitAnnotationListener.php
> +    public function getRateLimitsFromAttributes(string|array|object $controller): array
this can be private, it is not used anywhere else

2023-08-14 07:46 UTC, goetas approved these changes

2023-08-14 07:46 UTC, merged

2023-08-14 07:48 UTC, goetas commented
@axi  thanks a lot. while solving the conflicts i had to rebase your branch, but now somehow github show my face on the commit despite the fact that the commit is authored by you. :confused:

2023-08-14 08:08 UTC, axi commented
@goetas no worries, thanks for mentioning it